version: "3.8"
services:
  backend:
    build: .
    restart: always
    ports:
      - "8080:8080"

  frontend:
    build: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend